### ISSUE TITLE
ImportError: No module named http.server

### ISSUE THREAD

**Issue by Revozop** [p3nt4/Nuages#28] opened 2022-03-08 22:34 UTC
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\Nuages-master\Server\handlers\external\http\HTTPAES256Handler.py", line 2, in <module>
    from http.server import BaseHTTPRequestHandler, HTTPServer
ImportError: No module named http.server

console show this after i try use the module for start listener

**Comment by Revozop** [comment] 2022-03-08 22:35
i tried install pip http module but no work

**Comment by p3nt4** [comment] 2022-03-08 22:44
Yes the issue is with pip.

Try `!set python 1` to use "python3"

**Comment by p3nt4** [comment] 2022-03-09 14:14
I will close this for now, you can add a comment if it did not fix it.

**Closed by p3nt4** 2022-03-09 14:14 UTC

**Comment by Revozop** [comment] 2022-03-12 05:43
Worked, thanks

**Comment by p3nt4** [comment] 2022-03-13 16:29
Made a change to how modules call python.
The python path is now loaded from the configuration file.
https://github.com/p3nt4/Nuages/commit/99d7b8facd358276e0adb3c5c48c0dde1057976f
